In [2]:
import numpy as np
import pandas as pd

In [3]:
from sklearn import linear_model

In [4]:
model = linear_model.LinearRegression()#When we use linear regression syntax ,we give input as (y,x).
# While we give input to a model or any function,the input will be given as (x,y)

In [8]:
data = pd.read_csv("newone.csv")

In [9]:
type(data)

pandas.core.frame.DataFrame

In [10]:
data.head()

Unnamed: 0  atbat  hits  hmrun  runs  rbi  walks  years  catbat  chits  \
0           1    293    66      1    30   29     14      1     293     66   
1           2    315    81      7    24   38     39     14    3449    835   
2           3    479   130     18    66   72     76      3    1624    457   
3           4    496   141     20    65   78     37     11    5628   1575   
4           5    321    87     10    39   42     30      2     396    101   

     ...      cruns  crbi  cwalks  league division putouts  assists  errors  \
0    ...         30    29      14       A        E     446       33      20   
1    ...        321   414     375       N        W     632       43      10   
2    ...        224   266     263       A        W     880       82      14   
3    ...        828   838     354       N        E     200       11       3   
4    ...         48    46      33       N        E     805       40       4   

       salary  newLeague  
0  535.925882          A  
1  475.000000          N  
2  480.000000          A  
3  500.000000          N  
4   91.500000          N  

[5 rows x 21 columns]

In [ ]:
# MLR with TV, Radio,Newspaper

In [11]:
x = data [["atbat","hits","hmrun","runs","rbi","walks","years","putouts","assists","errors"]]

In [12]:
type(x)

pandas.core.frame.DataFrame

In [13]:
y = data ["salary"]

In [14]:
type(y)

pandas.core.series.Series

In [15]:
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [16]:
predictions = model.predict(x)

In [17]:
predictions[0:5] # these are the predictions developed after the model is developed

array([ 142.80662652,  714.74602701,  747.06782784,  708.21430428,
        490.49535198])

In [18]:
y[0:5] # y- actual value from the data (since we gave the original dataset as the train data to predict)

0    535.925882
1    475.000000
2    480.000000
3    500.000000
4     91.500000
Name: salary, dtype: float64

In [19]:
# R^2  
model.score(x,y) #(here I gave  x as TV,Radio,Newspaper "")

0.34567725654916504

In [20]:
model.coef_  #  beta1,beta2,....

array([ -2.18369549,   6.96280624,   0.88957999,   1.06848963,
         2.12025079,   3.92752495,  25.09661198,   0.23138224,
         0.18374067,  -2.82112247])

In [21]:
model.intercept_  # beta0

95.733216525565354

In [22]:
from sklearn import metrics

In [23]:
np.sqrt(metrics.mean_squared_error(predictions,y)) # RSE 

329.16187638314256

In [117]:
var = ["atbat","hits","hmrun","runs","rbi","catbat","chits","chmrun","cruns","crbi","walks","cwalks","years","putouts","assists","errors","league","newLeague","division"]

In [118]:
dummy = pd.get_dummies(data[var], drop_first = True )

In [119]:
dummy.head()

atbat  hits  hmrun  runs  rbi  catbat  chits  chmrun  cruns  crbi  walks  \
0    293    66      1    30   29     293     66       1     30    29     14   
1    315    81      7    24   38    3449    835      69    321   414     39   
2    479   130     18    66   72    1624    457      63    224   266     76   
3    496   141     20    65   78    5628   1575     225    828   838     37   
4    321    87     10    39   42     396    101      12     48    46     30   

   cwalks  years  putouts  assists  errors  league_N  newLeague_N  division_W  
0      14      1      446       33      20         0            0           0  
1     375     14      632       43      10         1            1           1  
2     263      3      880       82      14         0            0           1  
3     354     11      200       11       3         1            1           0  
4      33      2      805       40       4         1            1           0

In [120]:
x = dummy

In [153]:
# x = data [["catbat","chits","chmrun","cruns","crbi","atbat","hits","hmrun","runs","rbi","walks","years","putouts","assists","errors"]]

In [154]:
y = data ["salary"]

In [155]:
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [156]:
predictions = model.predict(x)

In [157]:
predictions[0:5]

array([  230.62563104,   330.57269877,   694.70688812,  1061.36050246,
         586.98021261])

In [158]:
y[0:5]

0    535.925882
1    475.000000
2    480.000000
3    500.000000
4     91.500000
Name: salary, dtype: float64

In [159]:
# R^2  
model.score(x,y)

0.45060492619281312

In [160]:
np.sqrt(metrics.mean_squared_error(predictions,y))

301.61705959592285