In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn import linear_model

In [3]:
model = linear_model.LinearRegression()#When we use linear regression syntax ,we give input as (y,x).
# While we give input to a model or any function,the input will be given as (x,y)

In [5]:
data = pd.read_csv("Advertising.csv")

In [12]:
type(data)

pandas.core.frame.DataFrame

In [14]:
data.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [ ]:
# MLR with TV, Radio,Newspaper

In [9]:
x = data [["TV","Radio","Newspaper"]]

In [15]:
type(x)

pandas.core.frame.DataFrame

In [10]:
y = data ["Sales"]

In [16]:
type(y)

pandas.core.series.Series

In [11]:
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [17]:
predictions = model.predict(x)

In [19]:
predictions[0:5] # these are the predictions developed after the model is developed

array([ 20.52397441,  12.33785482,  12.30767078,  17.59782951,  13.18867186])

In [20]:
y[0:5] # y- actual value from the data (since we gave the original dataset as the train data to predict)

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: Sales, dtype: float64

In [22]:
# R^2  
model.score(x,y) #(here I gave  x as TV,Radio,Newspaper "")

0.89721063817895208

In [24]:
model.coef_  #  beta1,beta2,....

array([ 0.04576465,  0.18853002, -0.00103749])

In [26]:
model.intercept_  # beta0

2.9388893694594067

In [36]:
newData = {'TV':[1,2],'Radio':[3,4],'Newspaper':[5,6]}  # I developed a model for 3 predictors.
#So,I need to give 3 predictors compulsorily when I access it using any dataframe.otherwise it shows up an error.
newData = pd.DataFrame(data = newData)
newData

Newspaper  Radio  TV
0          5      3   1
1          6      4   2

In [40]:
SalesPredictions = model.predict(newData)

In [41]:
from sklearn import metrics

In [43]:
np.sqrt(metrics.mean_squared_error(predictions,y)) # RSE 

2.7841263145109361

In [44]:
# EXERCISE

In [46]:
# Sales = b0 + b1 TV

In [47]:
x = data [["TV"]]

In [48]:
y = data ["Sales"]

In [49]:
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [50]:
predictions = model.predict(x)

In [51]:
predictions[0:5]

array([ 17.97077451,   9.14797405,   7.85022376,  14.23439457,  15.62721814])

In [52]:
model.score(x,y)

0.61187505085007099

In [53]:
model.coef_

array([ 0.04753664])

In [54]:
model.intercept_

7.032593549127693

In [55]:
np.sqrt(metrics.mean_squared_error(predictions,y)) # RSE 

3.2423221486546887

In [56]:
# Radio

In [57]:
x = data [["Radio"]]
y = data ["Sales"]
model.fit(x,y)
predictions = model.predict(x)
model.score(x,y) # R^2

0.33203245544529525

In [58]:
model.coef_

array([ 0.20249578])

In [59]:
model.intercept_

9.3116380951582833

In [60]:
np.sqrt(metrics.mean_squared_error(predictions,y)) # RSE 

4.2535159274564185

In [61]:
# Newspaper

In [62]:
x = data [["Newspaper"]]
y = data ["Sales"]
model.fit(x,y)
predictions = model.predict(x)
model.score(x,y) # R^2

0.052120445444305163

In [63]:
model.coef_ # beta1,..

array([ 0.0546931])

In [64]:
model.intercept_ # beta0

12.35140706927816

In [65]:
np.sqrt(metrics.mean_squared_error(predictions,y)) # RSE 

5.0669539883997068

In [66]:
x = data [["TV","Radio"]]  
y = data ["Sales"]
model.fit(x,y)
predictions = model.predict(x)
model.score(x,y) # R^2

0.89719426108289557

In [67]:
model.coef_ # beta1,..

array([ 0.04575482,  0.18799423])

In [68]:
model.intercept_ # beta0

2.9210999124051362

In [69]:
np.sqrt(metrics.mean_squared_error(predictions,y)) # RSE 

1.6687030593661929

In [ ]:
# interaction 

In [119]:
TV = data.TV
Radio = data.Radio
Newspaper = data.Newspaper

In [120]:
withinter = pd.DataFrame({'TV': TV,
                     'Radio':Radio,
                     'interaction':TV*Radio })
x = withinter
y = data ["Sales"]
model.fit(x,y)
predictions = model.predict(x)
model.score(x,y) # R^2

0.9677905498482523

In [121]:
model.coef_ # beta1,..

array([ 0.02886034,  0.01910107,  0.00108649])

In [122]:
model.intercept_ # beta0

6.7502202030751199

In [124]:
RSE = np.sqrt(metrics.mean_squared_error(predictions,y)) # RSE 
RSE

0.93403260817737821

In [129]:
RSE/(y.mean()) ## error %

0.066609563785158005